
package turnbasedstrategy;

/**
 *
 * @author cxz5100
 */
public class Characters extends javax.swing.JPanel {

    // Connect to the DB
    
    
    // Declare character name and stats variables
    String characterName;
    double physicalAttack;
    double specialAttack;
    double physicalDefence;
    double specialDefence;
    double critChance;
    double critDamage;
    double speed;
    double mana;
    double health;
    double dodge;
    double exp;
    
    /**
     * Creates new form Characters
     */
    public Characters() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Choose new character type and load base stats from the server
    public void newCharacter(){
        
    }
    
    // Choose previously saved character and load current stats
    public void loadCharacter(){
        
    }
    
    // Save current character level and stats
    public void saveCharacter(){
        
    }
    
    //This will take the move and the character stats and sends it to action class which will send it to the server    
    public void attackdamage(){
        
    }
    
    //This gets the attack damage the other players does and determines damage delt to the character
    public void defence(){
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
