/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package turnbasedstrategy;

/**
 *
 * @author cxz5100
 */
public class jpBattleground extends javax.swing.JPanel {

    
    private static String player1;
    private static String character1;
    private static String player2;
    private static String character2;
    /**
     * Creates new form jpBattleground
     */
    public jpBattleground() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(700, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void setPlayer(String p, String c){
        if(player1 == null){
            player1 = p;
            character1 = c;
        }
        else{
            player2 = p;
            character2 = c;
        }
    }
    
//                      jpBattleground battleground = new jpBattleground();
//                      battleground.setVisible(true);
//                      JDialog jdBattleground = new JDialog();
//                      JPanel Battleground = new jpBattleground();
//                      jdBattleground.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//                      jdBattleground.add(Battleground);
//                      jdBattleground.setSize(800, 600);
//                      jdBattleground.setModal(true);
//                      jpBattleground bjdBattleground.setVisible(true);
//                      Client.setClosed();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
