/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package turnbasedstrategy;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 * Class for the login page of the game.
 * 
 * @author  Cody Zerbe      4/3/17 - Created the file and most of the functionality
 *          Nick Beliveau   4/5/17 - Began commenting and renamed variables of visual components
 *                    Notes : Confused about the loop on line 177. Is this to get multiple results with the same name?
 */
public class jpLogin extends javax.swing.JPanel {

    //Database variables
    DBConnection connect = new DBConnection();
    Connection con = connect.connectToDB();
       
    //Variables for user interaction
    static String username;
    String password;
    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsMD;
    int column;
    String S;               //TODO Can we come up with a more meaningful name for this?
    JFrame frame;
    
    
    /**
     * Creates new form jpLogin
     */
    public jpLogin() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbLogin = new javax.swing.JButton();
        jbSignUp = new javax.swing.JButton();
        tfUsername = new javax.swing.JTextField();
        jlUsername = new javax.swing.JLabel();
        jlPassword = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();

        jbLogin.setText("Login");
        jbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginActionPerformed(evt);
            }
        });

        jbSignUp.setText("Sign Up");
        jbSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSignUpActionPerformed(evt);
            }
        });

        jlUsername.setText("Username:");

        jlPassword.setText("Password:");

        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbLogin)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlUsername)
                        .addGap(18, 18, 18)
                        .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbSignUp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlUsername))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlPassword)
                        .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(jbLogin)
                .addGap(76, 76, 76)
                .addComponent(jbSignUp)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Function to react to the sign up button being pressed. 
     * Opens the sign up panel
     * @param evt 
     */
    private void jbSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSignUpActionPerformed
        
        jpSignUp signUp = new jpSignUp();
        signUp.setVisible(true);
        JDialog jdSignUp = new JDialog();
        JPanel SignUp = new jpSignUp();
        jdSignUp.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jdSignUp.add(SignUp);
        jdSignUp.setSize(400, 300);
        jdSignUp.setModal(true);
        jdSignUp.setVisible(true);
        
    }//GEN-LAST:event_jbSignUpActionPerformed

    
    /**
     * Function to react to the log in button being pressed.
     * @param evt 
     */
    private void jbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginActionPerformed
        
        try 
        {
            //Get the text from both text fields
            username = tfUsername.getText();
            password = tfPassword.getText();
            
            //Get a result set of the player table
            ps = con.prepareStatement("SELECT username FROM player;");
            rs = ps.executeQuery();
            rsMD = rs.getMetaData();
            column = rsMD.getColumnCount();
            
            
            int y = 0;      //TODO Can we get a more meaningful name for the loop control?
            //TODO Make comment for this loop
            while(rs.next() == true)
            {
                for(int n = 1; n <= column; n++)
                {
                    S = rs.getString(n);
                    if(username.equals(S))
                        y++;
                }
            }
            
            if(y == 1)
            {
                ps = con.prepareStatement("SELECT password FROM player WHERE username = '" + username + "';");
                rs = ps.executeQuery();
                S = rs.getString(1);
                if(password.equals(S))
                {
                    y++;
                }
                else
                {
                    JOptionPane.showMessageDialog(frame, "The username and password do not match. Please try logging in again.", "Error", JOptionPane.ERROR_MESSAGE);
                }   
            }
            else{
                JOptionPane.showMessageDialog(frame, "Please sign up for an account.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            if(y == 2){             
                this.getTopLevelAncestor().setVisible(false);
                ps.close();
                con.close();
                jfPlayer player = new jfPlayer();
                player.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(jpLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbLoginActionPerformed

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbLogin;
    private javax.swing.JButton jbSignUp;
    private javax.swing.JLabel jlPassword;
    private javax.swing.JLabel jlUsername;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
